# From Python Lists to Numerical Arrays

- Suppose we want to perform a simple vector operation:

$$ \mathbf{x} = (1,2)^T
\qquad
\mathbf{y} = (10, 20)^T$$



- Using Python lists:

In [1]:
x = [1, 2]
y = [10, 20]

- We might want

$$ \mathbf{z}=2\mathbf{x}+\mathbf{y} $$

- But Python does not treat lists as mathematical vectors:

In [2]:
2*x + y

[1, 2, 1, 2, 10, 20]

- What did it do ??

- does $\textbf{not}$ perform vector arithmetic.

- How do we achieve what we want ?

- `*` does perform vector arithmetic. Same goes true for `+` as well 

- **Python does not know that `x` and `y` are mathematical vectors. It only knows that they are `list` objects.**

That's the conceptual point.

### Let OOP solve the problem

We can create a `Vector` class that knows how to perform

$$
\alpha\mathbf{x}
\qquad\text{and}\qquad
\mathbf{x}+\mathbf{y}.
$$

In [3]:
class TBTVEC:

    def __init__(self, x1, x2):
        self.x1 = x1
        self.x2 = x2

In [4]:
x = TBTVEC(1, 2)
y = TBTVEC(10, 20)

- What should $$ x + y $$ mean?

In [6]:
# z = x + y      # there to show the failure, uncomment to see

## Can we teach Python new operations ? 

- offcourse we can, duh !!!

- Using methods 

In [7]:
class TBTVEC2:

    def __init__(self, x1, x2):
        self.x1 = x1
        self.x2 = x2

    def add(self, other):
        return TBTVEC2(
        self.x1 + other.x1,
        self.x2 + other.x2)

    def scalar_multiply(self, alpha):
        return TBTVEC2(
        alpha * self.x1,
        alpha * self.x2)

In [8]:
# Now I am ready to add the two vectors x and y and mulitply by scalar
x = TBTVEC2(1, 2)
y = TBTVEC2(10, 20)

# x + y 
z = x.add(y)

print (z.x1)
print (z.x2)

# 2 * X
L = x.scalar_multiply(2)
print(L.x1)
print(L.x2)

# 2 * x + y

result = L.add(y)
print(result.x1)
print(result.x2)

11
22
2
4
12
24


### This works, but it does not look like the mathematics. 

## ugh !!!

- We would much rather write:

In [33]:
# 2*x + y

- Can we teach Python what `+` and `*` should mean for our Vector objects?

# Operator Overloading

- Python allows a class to define how operators behave when they are applied to its objects.

- Operator overloading allows us to define how standard Python operators behave for objects of a class.

- Operators such as +, -, *, /, and == can be given class-specific meanings.

- Python implements these operators through special methods, also called dunder methods.

- For example:
    - x + y → x.__add__(y)
    - x * y → x.__mul__(y)
    - x == y → x.__eq__(y)

- This allows objects to behave naturally according to the mathematical meaning we want.

- Why These Names

    - `__add__(y)`
    - `__mul__(y)`
    - `__eq__(y)`

Matter ??

- Python's built-in objects already have these operators implemented using the same special method names.

In [9]:
3 + 4

7

- is essentially handled through:

In [11]:
(3).__add__(4)

7

In [12]:
int.__add__(3, 4)

7

- Python therefore gives special meaning to method names such as:
    - `__add__` (+ operator)
    - `__sub__` (- operator)
    - `__mul__` (* operator)
    - `__truediv__`          (/ operator)
    - `__eq__` (= operator)
    - `__lt__` (< operator)

- These names are not arbitrary. 
- Python's interpreter recognizes them and uses them when the corresponding operators appear.
- Think of these special method names as part of Python's protocol.
- So when we define

In [39]:
# def __add__(self, other):

- we aren't simply creating a method called `__add__`.

- We are telling Python:
    - **When someone writes x + y and x is one of my objects, this is what + should do.**

## Lets do it with 2 X 1 Vec class 

In [17]:
class TBTVEC3:

    def __init__(self, x1, x2):
        self.x1 = x1
        self.x2 = x2

    def __add__(self, other):
        return TBTVEC3(
            self.x1 + other.x1,
            self.x2 + other.x2
        )

    def __mul__(self, alpha):
        return TBTVEC3(
            alpha * self.x1,
            alpha * self.x2
        )

    def __rmul__(self, alpha):
        return self.__mul__(alpha)

In [18]:
x = TBTVEC3(1, 2)
y = TBTVEC3(10, 20)
z = x * 2 + y

In [19]:
print(z.x1)
print(z.x2)

12
24


In [20]:
z = 2 * x + y

- Right multiplication has to be separately defined 

Exercise-1: Create your own complex-number class:
    - $$ z=a+bi.$$

Exercise-2: Define a `Polynomial` class

$$ p(x) = a_0 + a_1 x + a_2 x^2 + \ldots + a_n x^n $$

# Introduction to NumPy

## - We have seen that Python lists do not behave like mathematical vectors.


## - We therefore created our own `Vector` class and overloaded operators.

- An array is a ‘grid’ of values, with all the same type.

- But for numerical computing, we need to work with:
    - vectors with thousands or millions of entries,
    - matrices,
    - matrix-vector products,
    - numerical algorithms.

- Building all of this ourselves would be inefficient.

**NumPy provides efficient numerical array objects and operations.**

In [2]:
import numpy as np

`import numpy as np`
- Load the NumPy library so that I can use its functionality.
- as `np` This gives NumPy a short name.

- Instead of writing:
`numpy.array([1, 2, 3])`

- we can write: `np.array([1, 2, 3])`

- `np` is the standard convention

- `np` is not a Python keyword and NumPy isn't being renamed.

- It's simply a reference/alias:

numpy  ──────────────→  np

library           $\hspace{5.5cm}$                       alias

- **A library is reusable code written by someone else (or by us) that provides functionality we can import into our program.**

### How is a library organized?

Library
│
├── functions
├── classes
├── constants
└── submodules

### Make your library and use it 

# Back to NumPy

### Creating arrays

In [17]:
x = np.array([1, 2, 3, 4])   # 1-dimensional array (rank 1)
x

array([1, 2, 3, 4])

In [4]:
type(x)

numpy.ndarray

In [18]:
y = np.array([[1,2,3],[4,5,6]])     # 2-dimensional array (rank 2)

In [19]:
y.shape                             # the shape (rows,columns)

(2, 3)

In [20]:
y.size                              # number of elements

6

#### Some more ways to create standard arrays 

In [24]:
zeroarray = np.zeros((2, 3))             # 2x3 array with all elements 0

In [25]:
zeroarray

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
onesarray = np.ones((1,2))               # 1x2 array with all elements 1
onesarray

array([[1., 1.]])

In [27]:
fullarray = np.full((2,2),7)             # 2x2 array with all elements 7
fullarray

array([[7, 7],
       [7, 7]])

In [28]:
idenstitymat = np.eye(2)                    # 2x2 identity matrix
idenstitymat

array([[1., 0.],
       [0., 1.]])

In [29]:
arrange = np.arange(10)                # Evenly spaced values in an interval
arrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
prescarrange = np.linspace(0,9,10)
prescarrange

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
c = np.ones((3,3))
c 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
d = np.zeros((2,2,2))   # higher dimensional arrays
d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [94]:
d.shape

(2, 2, 2)

In [95]:
d.size

8

In [37]:
e = np.ones((3, 2), 'bool')  # 3x2 boolean array
e

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [38]:
f = np.zeros((3, 2), 'bool')  # 3x2 boolean array
f

array([[False, False],
       [False, False],
       [False, False]])

#### Arrays can also be stored and read from a (.npy) file (numpy.save(), numpy.load()):

In [39]:
np.save('array.npy', f)           # save the array f to a .npy file

In [40]:
g = np.load('array.npy')  
g 

array([[False, False],
       [False, False],
       [False, False]])

In [42]:
g.dtype

dtype('bool')

In [47]:
h = g.astype('int') # change datatype from boolean to integer
h 

array([[0, 0],
       [0, 0],
       [0, 0]])

-  `.astype('int')`, it will make a copy of the array, and re-allocate data - unless the dtype is exactly the same as before. 

#### Exercise
1.  Try out np.arange(10) and np.linspace(0,9,10), what is the difference? Can you adjust one to do the same as the other?
2.   Create a 3x2 array of random float numbers (check numpy.random.random()) between 0 and 1. Now change the arrays datatype to int (array.astype). How does the array look like?
3.   `Reshape` Create a 3x2 array of random integer numbers between 0 and 10. Change the shape of the array (check array.reshape) in any way possible. What is not possible?

In [97]:
randomarray = np.random.random((3,2))
randomarray

array([[0.58459233, 0.53628027],
       [0.1292946 , 0.83908003],
       [0.20447522, 0.02045705]])

In [98]:
randomarray.astype('int')

array([[0, 0],
       [0, 0],
       [0, 0]])

## Why NumPy???

#### NumPy is easy to deal with and greatly bug tested 

#### NumPy is fast 

In [99]:
a = list(range(10000))
b = [ 0 ] * 10000

In [100]:
%%timeit
for i in range(len(a)):
  b[i] = a[i]**2

388 μs ± 2.39 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


- This seems very fast. wait until the NumPy results!!


In [101]:
a = np.arange(10000)
b = np.zeros(10000)

In [102]:
%%timeit
b = a ** 2

3.68 μs ± 2.22 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


- Voila!!! around 100 times faster

### Vector arithmetic

In [50]:
x = np.array([1, 2])
y = np.array([10, 20])

In [51]:
z = 2*x + y

In [52]:
z

array([12, 24])

- NumPy has overloaded usual mathematical operators 

- Array shape

In [53]:
x.shape

(2,)

- This is a one-dimensional array with 2 entries.

In [54]:
A = np.array([
    [1, 2],
    [3, 4]
])

In [55]:
A.shape

(2, 2)

- 2 dimensional with 2 entries in each of the dimension 

In [11]:
A = np.array([[[1, 2],
    [3, 4]], [[5, 6],
    [7, 8]]])

In [12]:
A.shape

(2, 2, 2)

- ???

- By default, basic arithmetic (+, -, *, /) in NumPy is element-by-element.

- the operation is performed for each element in the array without you having to write a loop.

- an operation is “vectorized” when the looping over elements is carried out by NumPy internally, which uses specialized CPU instructions for this that greatly outperform a regular Python loop.

- `*` element-by-element multiplication

In [56]:
z = x*y
z

array([10, 40])

In [58]:
z = x @ y
z

np.int64(50)

- `@` symbol is used to perform matrix multiplication

In [59]:
B = np.array([[5,6],[7,8]])

In [60]:
# Addition
C = A + B
C

array([[ 6,  8],
       [10, 12]])

In [61]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12]])

- They are the same. What is happening in the above two how are they similar??

In [63]:
# Matrix multiplication
E = A @ B
E

array([[19, 22],
       [43, 50]])

In [64]:
E = np.dot(A, B)
E

array([[19, 22],
       [43, 50]])

- The same thing happens here as well

In [108]:
A = ([[1, 2, 3],[1, 2, 3]])
B = 1.0

C = np.dot(A, B)
C

array([[1., 2., 3.],
       [1., 2., 3.]])

### Exercise 
1. $\textbf{Matrix multiplication:}$ What is the difference between numpy.multiply and numpy.dot() ? Try calling these functions with either x, y (1D arrays) or a, b (2D arrays) as input and observe the behaviour.
2. $\textbf{Axis:}$ What is the difference between np.sum(a, axis=1) vs np.sum(a, axis=0) on a two-dimensional array? What if you leave out the axis parameter?

### Indexing and Slicing

- There are many different choices to extract values out of a NumPy array

      - select a single element
  
      - select rows or columns

      - select ranges where a condition is true.

#### select a single element

In [66]:
a = np.arange(16).reshape(4, 4)  # 4x4 matrix from 0 to 15
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- extracting columns 

In [67]:
a[:,0]   

array([ 0,  4,  8, 12])

- extracting submatrices 

In [68]:
a[1:3,1:3] 

array([[ 5,  6],
       [ 9, 10]])

- choosing more than one element 

In [69]:
a[(0, 1), (1, 1)]

array([1, 5])

In [75]:
a.max()

np.int64(15)

- Boolean indexing on above created array:

In [72]:
idx = (a > 0)      # creates boolean matrix of same size as a
idx


array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
a[idx]             # array with matching values of above criterion

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

- From `a`, give me the elements at positions where idx is True."

- In one go the same can be achieved 

In [74]:
a[a > 0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Exercise: 
1. $\textbf{Select positive numbers:}$ 

    a = np.array([-3, 5, -1, 7, 0, -4, 2])

    - Create a Boolean array that identifies the positive elements.
    - Use Boolean indexing to extract all positive elements.
    - Extract all negative elements.
    - Extract all elements that are zero.
      
2. $\textbf{Replace negative values:}$

   a = np.array([4, -2, 7, -5, 3, -1, 8])

   - Use Boolean indexing to replace all negative values with zero.
  
3. $\textbf{Values in an interval:}$

   x = np.array([-3, 1, 4, 7, 10, 12, 15])

   - Extract all values satisfying $5 \leq x \leq 12$.

4. $\textbf{Filtering exam marks:}$

   marks = np.array([45, 72, 38, 91, 56, 64, 29, 83, 77, 49])

   Use Boolean indexing to:

    - Find all students who passed (marks >= 40).
    - Find all students who scored at least 75.
    - Find all students who scored between 50 and 70.
    - Find the number of students who failed.
 

## Linear algebra and other advanced math

- Internally, NumPy doesn’t invent its own math routines: it relies on BLAS and LAPACK to do this kind of math - the same as many other languages.

- NumPy provides linear algebra operations through the `np.linalg` submodule

- Solving a system of linear equations
- Consider:
  
    $ 2 x + y = 5$
  
    $ x + 3 y = 6$.

In [76]:
# Matrix and vectors
A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 6])

In [77]:
# Solve A x = b
x = np.linalg.solve(A, b)

In [78]:
print("A =")
print(A)

A =
[[2 1]
 [1 3]]


In [79]:
print("\nb =")
print(b)

print("\nSolution x =")
print(x)


b =
[5 6]

Solution x =
[1.8 1.4]


In [80]:
# Check the solution
print("\nCheck A @ x =")
print(A @ x)


Check A @ x =
[5. 6.]


- Matrix transpose

In [82]:
# Transpose
AT = A.T
AT

array([[2, 1],
       [1, 3]])

- Determinant

In [85]:
detA = np.linalg.det(A)
print("detA = ", detA)

detA =  5.000000000000001


- Inverse

In [88]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0.6, -0.2],
       [-0.2,  0.4]])

- Norm of a vector

In [89]:
norm_x = np.linalg.norm(x)
norm_x

np.float64(2.2803508501982757)

- Eigenvalues and eigenvectors

In [90]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [91]:
print("||x|| =", norm_x)
print("Eigenvalues =", eigenvalues)
print("Eigenvectors =\n", eigenvectors)

||x|| = 2.2803508501982757
Eigenvalues = [1.38196601+0.j 3.61803399+0.j]
Eigenvectors =
 [[-0.85065081+0.j -0.52573111+0.j]
 [ 0.52573111+0.j -0.85065081+0.j]]


### Note that: NumPy arrays themselves are the main data structure

- while np.linalg provides the linear-algebra algorithms

## Why do we need numerical methods?

- imagine $ A x = b $

  where

  $A \in \mathbb{R}^{1000 \times 1000}$

- we don't necessarily want to compute the inverse directly.

- Instead, we develop algorithms such as:

      - Gaussian elimination
      - LU decomposition
      - QR decomposition
      - Conjugate gradient
      - GMRES 